export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST"
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS"
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL"

export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST"
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const GET_BLOG_FAIL = "GET_BLOG_FAIL"